### ISSUE TITLE
Slide image change

### ISSUE THREAD

**Issue by shubham007kumar** [Bhargav1224/Nitrogen-IndieGogo#7]
Getting error after one complete loop
![Screenshot (194)](https://user-images.githubusercontent.com/34106521/114781384-37196b00-9d96-11eb-95d5-8a94f34aa3bb.png)
![Screenshot (193)](https://user-images.githubusercontent.com/34106521/114781387-397bc500-9d96-11eb-9399-4da018801e03.png)

**Comment by Bhargav1224** [comment]
Try to use Array of images URLs instead of Array of objects and also use ternary operator for the conditions.
